import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// components
import MenuBar from "@/components/layout/menu-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen w-screen bg-neutral-50 font-inter text-gray-700">
          {/** menu bar */}
          
          <div className="flex flex-grow flex-col">
            {/** content */}
            <div className="flex flex-grow flex-col overflow-auto">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
